### ISSUE TITLE
Enrollment Exception

### ISSUE THREAD

**Issue by xl-gtf** [bikram990/PyScep#7]
Hi Bikramjeet,
I am looking into your interesting SCEP client solution and trying out your example. So, I have copied in your example and call:
generate_self_signed
generate_csr
client(here I provide my own url)
enrol(here I provide my own identifier)

When enrolling, the capabilities and 3 certficates are retrieved, an envelope is created and the pki operation dispatched. The reply SCEPMessage is then parsed, which includes verifying public key - and here I get an exception - the EVP_PKEY_verify returns 0 and your code raises InvalidSignature.

How do I proceed from here? 

BR Christian

**Comment by bikram990** [comment]
@xl-gtf Could you please verify what algo your server is using?

https://github.com/bikram990/PyScep/blob/main/src/scep/Client/message.py#L59

This library supports only `rsassa_pkcs1v15`
