### ISSUE TITLE
feature request: support for passwords in the client

### ISSUE THREAD

**Issue by CharlPels** [bikram990/PyScep#8]
For testing of solutuons like scepman I would like to use PyScep however it seems that I can only profide a url and not a "static" password.

client = Client.Client(
    url = 'https://scepman-app-<random>.azurewebsites.net/static',
    password = '<password>'
)

https://docs.scepman.com/certificate-deployment/static-certificates

**Comment by bikram990** [comment]
@CharlPels This is already supported. Please check [this](https://github.com/bikram990/PyScep#signing-request)
